version: '3'
services:
  web:
      build: .
      restart: unless-stopped
      expose:
        - '8443'
      environment:        
        - SPRING_DATASOURCE_URL=jdbc:mysql://database/eFightClub_schema
      deploy:
        mode: loadbalancer
        replicas: 2
      depends_on:
        - database
  database: 
    image: mysql:8
    hostname: master
    container_name: database
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=WoozyGuy
      - MYSQL_DATABASE=eFightClub_schema