version: '3'
services:
  database: 
    image: mysql:8
    hostname: master
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=WoozyGuy
      - MYSQL_DATABASE=eFightClub_schema
  web:
      build: eFightClub/.
      restart: unless-stopped
      expose:
        - '8443'
      environment:        
        - SPRING_DATASOURCE_URL=jdbc:mysql://database/eFightClub_schema
      deploy:
        mode: loadbalancer
        replicas: 2
      depends_on:
        - database
  rabbitmq:
    image: rabbitmq
  loadbalancer:
    image: haproxy:2.7.3
    ports:
      - "8443:443" #Unico puerto abierto web, conecta con Haproxy
      - "8181:8181" #Puerto para ver Stats
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    restart: unless-stopped